name: "Import config factions data"
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Powers data import
      shell: bash
      run: python scripts/power-data.py --config-json hq-config.json --indent 0

    - name: Factions data import
      shell: bash
      run: python scripts/faction-data.py --config-json hq-config.json --indent 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Generate factions meta
      shell: bash
      run: node scripts/generate-meta.js

    - name: Set up Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git

    - name: Commit changes
      shell: bash
      run: |
        git add public/datasets/meta.js -f
        git add public/datasets/**/* -f
        git commit -m "Daily factions data import" || echo "No changes to commit"
        git push origin HEAD
